update workflows

diff --git a/.github/workflows/pre-publish.yaml b/.github/workflows/pre-publish.yaml
--- a/.github/workflows/pre-publish.yaml
+++ b/.github/workflows/pre-publish.yaml
@@ -29,8 +29,8 @@ jobs:
           git config user.email "${{ github.actor}}@users.noreply.github.com"
 
           # To deploy the application with the latest changes, packages versions must be up to date.
-          npx lerna version --conventional-commits --conventional-graduate --no-changelog --yes
-          npx lerna publish from-git --yes
+          npx lerna version --conventional-commits --conventional-prerelease --no-changelog --preid "alpha" --yes
+          npx lerna publish from-git --dist-tag alpha --yes
 
       - name: "Update package.json with latest library version"
         run: |
@@ -39,10 +39,22 @@ jobs:
           
           # To deploy the application with the latest changes, packages versions must be up to date.
           for pkg in "${package_names[@]}"; do
-            latest_version=$(npm view "@zidabah/$pkg" version)
-            jq --arg latest_version "$latest_version" ".dependencies[\"@zidabah/$pkg\"] = \$latest_version" package.json > package.json.tmp
-            mv package.json.tmp package.json
+            latest_version=$(npm view "@zidabah/$pkg" dist-tags.alpha 2>/dev/null)
+          
+            # Check if npm show command was successful (exit code 0)
+            if [ $? -eq 0 ]; then
+              jq --arg latest_version "$latest_version" ".dependencies[\"@zidabah/$pkg\"] = \$latest_version" package.json > package.json.tmp
+              mv package.json.tmp package.json
+            else
+              echo "Package '@zidabah/$pkg' doesn't have an alpha version."
+            fi
           done
+
+          # note: clean up temporary files
+          rm -f package.json.tmp
+
+          # note: install dependencies with the updated package.json
+          npm install
 
       - name: "Commit and push changes"
         run: |
